version: "3"

# Automatically load environment variables
dotenv: [".env.local", ".env"]

vars:
  SRH_NAME: '{{.SRH_NAME | default "sw-srh"}}'
  SRH_IMAGE: '{{.SRH_IMAGE | default "hiett/serverless-redis-http:latest"}}'
  SRH_PORT: "{{.SRH_PORT | default 8080}}"

tasks:
  env-setup:
    desc: "Create .env.local interactively"
    cmds:
      - task: env-setup:windows
        platforms: [windows]
      - task: env-setup:posix
        platforms: [linux, darwin]

  env-setup:windows:
    internal: true
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File ./setup-env.ps1

  env-setup:posix:
    internal: true
    cmds:
      - sh ./setup-env.sh

  dev:
    desc: "Start development environment"
    deps: [ensure-srh]
    cmds:
      - npm run dev

  ensure-srh:
    desc: "Start SRH container if not running"
    # Only run if the container isn't already active
    status:
      - docker ps --filter "name={{.SRH_NAME}}" --filter "status=running" -q
    cmds:
      - |
        docker start {{.SRH_NAME}} 2>/dev/null || \
        docker run -d -p {{.SRH_PORT}}:80 --name {{.SRH_NAME}} \
          -e SRH_MODE=env \
          -e SRH_TOKEN="{{.SRH_TOKEN}}" \
          -e SRH_CONNECTION_STRING="{{.SRH_CONNECTION_STRING}}" \
          -e SRH_EMAIL="{{.EMAIL}}" \
          {{.SRH_IMAGE}}
      - task: wait-for-srh

  wait-for-srh:
    internal: true
    desc: "Health check for SRH"
    cmds:
      - |
        for i in $(seq 1 30); do
          if curl -s "http://localhost:{{.SRH_PORT}}/" > /dev/null; then
            echo "SRH is up."
            exit 0
          fi
          sleep 1
        done
        echo "SRH failed to start." >&2
        exit 1

  stop-srh:
    desc: "Stop and remove SRH"
    cmds:
      - docker rm -f {{.SRH_NAME}}
    ignore_error: true

  logs-srh:
    desc: "Tail SRH logs"
    cmds:
      - docker logs -f {{.SRH_NAME}}
